/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.wg.os.ui.setup;

import com.mongodb.client.result.DeleteResult;
import com.wg.os.common.Global;
import com.wg.os.document.Payment;
import com.wg.os.service.PaymentService;
import com.wg.os.ui.common.PaymentTabelModel;
import com.wg.os.util.Util1;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author Lenovo
 */
@Component
public class PaymentSetup extends javax.swing.JPanel {

    private static final Logger LOGGER = LoggerFactory.getLogger(PaymentSetup.class);
    private Payment payment;
    private int selectRow = -1;

    @Autowired
    private PaymentTabelModel paymentTabelModel;
    @Autowired
    private PaymentService paymentService;

    /**
     * Creates new form CitySetup
     */
    public PaymentSetup() {
        initComponents();
    }

    public void initTabel() {
        Util1.setLookAndFeel(this);
        setCurrentFont();
        tblPayment.setModel(paymentTabelModel);
        paymentTabelModel.setlistCustomer(paymentService.findAll());
        tblPayment.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblPayment.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
            if (e.getValueIsAdjusting()) {
                if (tblPayment.getSelectedRow() >= 0) {
                    selectRow = tblPayment.convertRowIndexToModel(tblPayment.getSelectedRow());
                }

            }
        });
        tblPayment.getInputMap().put(KeyStroke.getKeyStroke("DELETE"), "Del-Action");
        tblPayment.getActionMap().put("Del-Action", actionItemDelete);

    }
    private final Action actionItemDelete = new AbstractAction() {

        @Override
        public void actionPerformed(ActionEvent e) {
            int row = tblPayment.getSelectedRow();

            if (row >= 0) {
                try {
                    int showConfirmDialog = JOptionPane.showConfirmDialog(Global.parentFrame, "Are you sure to Delete");
                    if (showConfirmDialog == JOptionPane.YES_OPTION) {
                        Payment payment = paymentTabelModel.getPayment(row);
                        DeleteResult remove = paymentService.remove(payment.getId());
                        if (remove.getDeletedCount() == 1) {
                            paymentTabelModel.deletePayment(row);
                        }
                    }
                } catch (HeadlessException ex) {
                    LOGGER.info("Remove Payment :" + ex.getMessage());
                }
            }
        }
    };

    private void save() {

        try {
            if (isValidEntry()) {
                paymentTabelModel.addPayment(payment);
            }
        } catch (HeadlessException e) {
            LOGGER.error("saveCity  :" + e.getMessage());
        }
    }

    private boolean isValidEntry() {
        boolean status = false;
        String cityName = txtPayment.getText();
        if (cityName.isEmpty()) {
            JOptionPane.showMessageDialog(new JFrame(), "Field Cannot be empty...", "Payment Setup", JOptionPane.ERROR_MESSAGE);
            status = false;
        } else {
            payment = new Payment();
            payment.setPayment(cityName);
            Payment save = paymentService.save(payment);
            if (save != null) {
                clear();
                JOptionPane.showMessageDialog(Global.parentFrame, "Save");
                status = true;
            }
        }
        return status;
    }

    private void clear() {
        txtPayment.setText("");
        tblPayment.getSelectionModel().clearSelection();

    }

    private void setCurrentFont() {
        java.awt.Component[] components = getComponents();
        for (java.awt.Component com : components) {
            com.setFont(Global.font);
        }
        tblPayment.setFont(Global.font);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPayment = new javax.swing.JTable();
        txtPayment = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        tblPayment.setFont(Global.font);
        tblPayment.setRowHeight(20);
        jScrollPane1.setViewportView(tblPayment);

        txtPayment.setFont(Global.font);
        txtPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaymentActionPerformed(evt);
            }
        });

        jLabel2.setFont(Global.font);
        jLabel2.setText("Payment");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        LOGGER.info("CitySetup Component Shown");

    }//GEN-LAST:event_formComponentShown

    private void txtPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaymentActionPerformed
        // TODO add your handling code here:
        save();
    }//GEN-LAST:event_txtPaymentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPayment;
    private javax.swing.JTextField txtPayment;
    // End of variables declaration//GEN-END:variables
}
