/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.wg.os.ui.setup;

import com.wg.os.common.Global;
import com.wg.os.common.GlobalColor;
import com.wg.os.util.Util1;
import java.awt.Dialog;
import java.io.IOException;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JLabel;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author Lenovo
 */
@Component
public class SetupMainPanel extends javax.swing.JPanel {

    private static final org.slf4j.Logger LOGGER = LoggerFactory.getLogger(SetupMainPanel.class);

    @Autowired
    private CitySetup citySetup;
    @Autowired
    private ColorSetup colorSetup;
    @Autowired
    private SizeSetup sizeSetup;
    @Autowired
    private AccountSetup accountSetup;
    @Autowired
    private PaymentSetup paymentSetup;
    @Autowired
    private ExpenseSetup expenseSetup;
    @Autowired
    private GenderSetup genderSetup;

    /**
     * Creates new form SetupMainPanel
     */
    public SetupMainPanel() {
        initComponents();

    }

    private void setCitySetup(JDialog dialog) {
        ImageIcon user = new ImageIcon(getClass().getResource("/image/city_icon.png"));
        dialog.setIconImage(user.getImage());
        dialog.setTitle("City Setup");
        citySetup.initTabel();
        dialog.add(citySetup);
    }

    private void setColorSetup(JDialog dialog) {
        ImageIcon color = new ImageIcon(getClass().getResource("/image/color_icon.png"));
        dialog.setIconImage(color.getImage());
        dialog.setTitle("Color Setup");
        colorSetup.initTabel();
        dialog.add(colorSetup);
    }

    private void setAccountSetup(JDialog dialog) {
        ImageIcon color = new ImageIcon(getClass().getResource("/image/account_icon.png"));
        dialog.setIconImage(color.getImage());
        dialog.setTitle("Account Setup");
        accountSetup.initTabel();
        dialog.add(accountSetup);
    }

    private void setSizeSetup(JDialog dialog) {
        ImageIcon size = new ImageIcon(getClass().getResource("/image/size_icon.png"));
        dialog.setIconImage(size.getImage());
        dialog.setTitle("Size Setup");
        sizeSetup.initTabel();
        dialog.add(sizeSetup);
    }

    private void setPayment(JDialog dialog) {
        ImageIcon size = new ImageIcon(getClass().getResource("/image/size_icon.png"));
        dialog.setIconImage(size.getImage());
        dialog.setTitle("Payment Setup");
        paymentSetup.initTabel();
        dialog.add(paymentSetup);
    }

    private void setExpense(JDialog dialog) {
        ImageIcon size = new ImageIcon(getClass().getResource("/image/expense.png"));
        dialog.setIconImage(size.getImage());
        dialog.setTitle("Expense Setup");
        expenseSetup.initTabel();
        dialog.add(expenseSetup);
    }

    private void setGender(JDialog dialog) {
        ImageIcon size = new ImageIcon(getClass().getResource("/image/expense.png"));
        dialog.setIconImage(size.getImage());
        dialog.setTitle("Gender Setup");
        genderSetup.initTabel();
        dialog.add(genderSetup);
    }

    private void openJDialog(String dType) throws IOException {
        JDialog dialog = new JDialog(Global.parentFrame, Dialog.ModalityType.DOCUMENT_MODAL);
        switch (dType) {
            case "CitySetup":
                setCitySetup(dialog);
                break;
            case "ColorSetup":
                setColorSetup(dialog);
                break;
            case "SizeSetup":
                setSizeSetup(dialog);
                break;
            case "AccountSetup":
                setAccountSetup(dialog);
                break;
            case "PaymentSetup":
                setPayment(dialog);
            case "ExpenseSetup":
                setExpense(dialog);
                break;
            case "GenderSetup":
                setGender(dialog);
                break;
            default:
                break;
        }
        dialog.setSize(490, 420);
        dialog.setResizable(false);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }

    private void setCurrentFont() {
        java.awt.Component[] components = getComponents();
        for (java.awt.Component com : components) {
            com.setFont(Global.font);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCitySetup = new javax.swing.JLabel();
        labelColorSetup = new javax.swing.JLabel();
        labelSizeSetup = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelAccount = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelExpense = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblGenderSetup = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        labelCitySetup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCitySetup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/city_icon.png"))); // NOI18N
        labelCitySetup.setToolTipText("City Setup");
        labelCitySetup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelCitySetupMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelCitySetupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelCitySetupMouseExited(evt);
            }
        });

        labelColorSetup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelColorSetup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/color_icon.png"))); // NOI18N
        labelColorSetup.setToolTipText("Color Setup");
        labelColorSetup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelColorSetupMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelColorSetupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelColorSetupMouseExited(evt);
            }
        });

        labelSizeSetup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSizeSetup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/size_icon.png"))); // NOI18N
        labelSizeSetup.setToolTipText("Size Setup");
        labelSizeSetup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelSizeSetupMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelSizeSetupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelSizeSetupMouseExited(evt);
            }
        });

        jLabel1.setFont(Global.font);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("City Setup");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(Global.font);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Color Setup");
        jLabel2.setToolTipText("");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel3.setFont(Global.font);
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Size Setup");
        jLabel3.setToolTipText("");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelAccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/account_icon.png"))); // NOI18N
        labelAccount.setToolTipText("Account");
        labelAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAccountMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelAccountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelAccountMouseExited(evt);
            }
        });

        jLabel4.setFont(Global.font);
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Account");
        jLabel4.setToolTipText("");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelExpense.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelExpense.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/expense.png"))); // NOI18N
        labelExpense.setToolTipText("Expense Setup");
        labelExpense.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelExpenseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelExpenseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelExpenseMouseExited(evt);
            }
        });

        jLabel6.setFont(Global.font);
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Expense Setup");
        jLabel6.setToolTipText("");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblGenderSetup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGenderSetup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/gender.png"))); // NOI18N
        lblGenderSetup.setToolTipText("Size Setup");
        lblGenderSetup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGenderSetupMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblGenderSetupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblGenderSetupMouseExited(evt);
            }
        });

        jLabel5.setFont(Global.font);
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Gender Setup");
        jLabel5.setToolTipText("");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCitySetup, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelColorSetup, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelSizeSetup, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblGenderSetup, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelExpense, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelColorSetup, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCitySetup, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSizeSetup, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGenderSetup, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel6)
                        .addComponent(jLabel4)))
                .addGap(351, 351, 351))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6});

    }// </editor-fold>//GEN-END:initComponents

    private void labelCitySetupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCitySetupMouseClicked
        try {
            // TODO add your handling code here:
            openJDialog("CitySetup");
        } catch (IOException ex) {
            LOGGER.error("Open City Setup :" + ex.getMessage());
        }
    }//GEN-LAST:event_labelCitySetupMouseClicked

    private void labelColorSetupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelColorSetupMouseClicked
        try {
            // TODO add your handling code here:
            openJDialog("ColorSetup");
        } catch (IOException ex) {
            LOGGER.error("Open Color Setup :" + ex.getMessage());
        }
    }//GEN-LAST:event_labelColorSetupMouseClicked

    private void labelSizeSetupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSizeSetupMouseClicked
        try {
            // TODO add your handling code here:
            openJDialog("SizeSetup");
        } catch (IOException ex) {
            LOGGER.error("Open Size Setup :" + ex.getMessage());
        }
    }//GEN-LAST:event_labelSizeSetupMouseClicked

    private void labelAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAccountMouseClicked
        try {
            // TODO add your handling code here:
            openJDialog("AccountSetup");
        } catch (IOException ex) {
            LOGGER.error("Open Account Setup :" + ex.getMessage());
        }
    }//GEN-LAST:event_labelAccountMouseClicked

    private void labelAccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAccountMouseEntered
        // TODO add your handling code here:
        labelAccount.setBorder(BorderFactory.createLineBorder(GlobalColor.borderColor, 1, true));
    }//GEN-LAST:event_labelAccountMouseEntered

    private void labelAccountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAccountMouseExited
        // TODO add your handling code here
        labelAccount.setBorder(null);
    }//GEN-LAST:event_labelAccountMouseExited

    private void labelCitySetupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCitySetupMouseEntered
        // TODO add your handling code here:
        labelCitySetup.setBorder(BorderFactory.createLineBorder(GlobalColor.borderColor, 1, true));
    }//GEN-LAST:event_labelCitySetupMouseEntered

    private void labelCitySetupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCitySetupMouseExited
        // TODO add your handling code here:
        labelCitySetup.setBorder(null);
    }//GEN-LAST:event_labelCitySetupMouseExited

    private void labelColorSetupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelColorSetupMouseEntered
        // TODO add your handling code here:
        labelColorSetup.setBorder(BorderFactory.createLineBorder(GlobalColor.borderColor, 1, true));
    }//GEN-LAST:event_labelColorSetupMouseEntered

    private void labelColorSetupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelColorSetupMouseExited
        // TODO add your handling code here:
        labelColorSetup.setBorder(null);
    }//GEN-LAST:event_labelColorSetupMouseExited

    private void labelSizeSetupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSizeSetupMouseEntered
        // TODO add your handling code here:
        labelSizeSetup.setBorder(BorderFactory.createLineBorder(GlobalColor.borderColor, 1, true));
    }//GEN-LAST:event_labelSizeSetupMouseEntered

    private void labelSizeSetupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSizeSetupMouseExited
        // TODO add your handling code here:
        labelSizeSetup.setBorder(null);
    }//GEN-LAST:event_labelSizeSetupMouseExited

    private void labelExpenseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelExpenseMouseClicked
        try {
            // TODO add your handling code here:
            openJDialog("ExpenseSetup");
        } catch (IOException ex) {
            LOGGER.error("Open Expense Setup :" + ex.getMessage());
        }
    }//GEN-LAST:event_labelExpenseMouseClicked

    private void labelExpenseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelExpenseMouseEntered
        // TODO add your handling code here:
        labelExpense.setBorder(BorderFactory.createLineBorder(GlobalColor.borderColor, 1, true));
    }//GEN-LAST:event_labelExpenseMouseEntered

    private void labelExpenseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelExpenseMouseExited
        // TODO add your handling code here:
        labelExpense.setBorder(null);
    }//GEN-LAST:event_labelExpenseMouseExited

    private void lblGenderSetupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGenderSetupMouseClicked
        try {
            // TODO add your handling code here:
            openJDialog("GenderSetup");
        } catch (IOException ex) {
            LOGGER.error("Open Gender Setup :" + ex.getMessage());
        }
    }//GEN-LAST:event_lblGenderSetupMouseClicked

    private void lblGenderSetupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGenderSetupMouseEntered
        // TODO add your handling code here:
        lblGenderSetup.setBorder(BorderFactory.createLineBorder(GlobalColor.borderColor, 1, true));

    }//GEN-LAST:event_lblGenderSetupMouseEntered

    private void lblGenderSetupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGenderSetupMouseExited
        // TODO add your handling code here:
        lblGenderSetup.setBorder(null);

    }//GEN-LAST:event_lblGenderSetupMouseExited

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        setCurrentFont();
        Util1.setLookAndFeel(this);

    }//GEN-LAST:event_formComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel labelAccount;
    private javax.swing.JLabel labelCitySetup;
    private javax.swing.JLabel labelColorSetup;
    private javax.swing.JLabel labelExpense;
    private javax.swing.JLabel labelSizeSetup;
    private javax.swing.JLabel lblGenderSetup;
    // End of variables declaration//GEN-END:variables
}
