/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.wg.os.ui.setting;

import com.wg.os.common.Global;
import com.wg.os.document.CurrentFont;
import com.wg.os.document.Setting;
import com.wg.os.service.SettingService;
import com.wg.os.util.Util1;
import java.awt.Font;
import java.io.IOException;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author Lenovo
 */
@Component
public class FontPanel extends javax.swing.JPanel {

    private static final Logger LOGGER = LoggerFactory.getLogger(FontPanel.class);
    @Autowired
    private SettingService settingService;

    /**
     * Creates new form FontPanel
     */
    public FontPanel() {
        initComponents();
    }

    public void setSelectedFont() {
        Util1.setLookAndFeel(this);
        setCurrentFont();
        fontChooser.setSelectedFont(Global.font);
    }

    private void setCurrentFont() {
        java.awt.Component[] fcComps = panelFC.getComponents();
        for (java.awt.Component fcComp : fcComps) {
            fcComp.setFont(Global.font);
        }
    }

    private void save() {
        Font selectedFont = fontChooser.getSelectedFont();
        CurrentFont font = new CurrentFont();
        font.setFontName(selectedFont.getFontName());
        font.setFontSize(selectedFont.getSize());
        font.setFontStyle(selectedFont.getStyle());
        Global.setting.setFont(font);
        settingService.save(Global.setting);
        int showConfirmDialog = JOptionPane.showConfirmDialog(Global.parentFrame, "You need to restart...");
        if (showConfirmDialog == JOptionPane.OK_OPTION) {
            restart();
        }
    }

    private void restart() {
        try {
            String rtPath = Global.setting.getRetartPath();
            Runtime.getRuntime().exec("java -jar " + rtPath);
        } catch (IOException ex) {
            LOGGER.error("Restart Program :" + ex.getMessage());
        }
        System.exit(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFC = new javax.swing.JPanel();
        fontChooser = new say.swing.JFontChooser();
        jButton1 = new javax.swing.JButton();

        panelFC.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                panelFCComponentShown(evt);
            }
        });

        jButton1.setText("Apply");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFCLayout = new javax.swing.GroupLayout(panelFC);
        panelFC.setLayout(panelFCLayout);
        panelFCLayout.setHorizontalGroup(
            panelFCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fontChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFCLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        panelFCLayout.setVerticalGroup(
            panelFCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFCLayout.createSequentialGroup()
                .addComponent(fontChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        save();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void panelFCComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_panelFCComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_panelFCComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private say.swing.JFontChooser fontChooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel panelFC;
    // End of variables declaration//GEN-END:variables
}
